name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'

  yaml-validation:
    name: YAML Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Validate YAML frontmatter
        run: |
          # Check all SKILL.md files have valid YAML frontmatter
          find . -name "SKILL.md" -type f | while read -r file; do
            echo "Checking YAML frontmatter in $file"
            # Extract YAML frontmatter between --- markers
            awk '/^---$/{i++; if(i==2) exit; next} i==1' "$file" > /tmp/frontmatter.yml
            if [ -s /tmp/frontmatter.yml ]; then
              yamllint /tmp/frontmatter.yml || exit 1
            else
              echo "Warning: No YAML frontmatter found in $file"
            fi
          done

      - name: Validate workflow YAML files
        run: |
          if [ -d .github/workflows ]; then
            yamllint .github/workflows/*.yml
          fi

  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/link-check-config.json'

  file-validation:
    name: File Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for trailing whitespace
        run: |
          if grep -r '[[:blank:]]$' --include="*.md" --include="*.yml" --include="*.yaml" .; then
            echo "Error: Found trailing whitespace"
            exit 1
          fi

      - name: Validate skill structure
        run: |
          # Find all leaf directories (skill directories) and validate them
          # A leaf directory is one that has no subdirectories
          # Exclude resource directories: templates, scripts, references, assets

          # Find all directories excluding .git, .github, and docs
          find . -type d -not -path '*/\.*' -not -path './docs*' | while read -r dir; do
            # Skip root directory
            if [ "$dir" = "." ]; then
              continue
            fi

            # Get the directory name (basename)
            dirname=$(basename "$dir")

            # Skip resource directories (these are bundled resources, not skills)
            if [ "$dirname" = "templates" ] || [ "$dirname" = "scripts" ] || \
               [ "$dirname" = "references" ] || [ "$dirname" = "assets" ]; then
              echo "Skipping resource directory: $dir"
              continue
            fi

            # Check if this directory is a leaf (has no subdirectories)
            subdir_count=$(find "$dir" -mindepth 1 -maxdepth 1 -type d | wc -l)

            # If it's a leaf directory (no subdirectories), it should have SKILL.md
            if [ "$subdir_count" -eq 0 ]; then
              # Check SKILL.md exists (required)
              if [ ! -f "${dir}/SKILL.md" ]; then
                echo "Error: ${dir}/SKILL.md not found (required for leaf directory)"
                exit 1
              fi
              echo "✓ ${dir}/SKILL.md found"

              # Check for required frontmatter fields
              if ! grep -q "^name:" "${dir}/SKILL.md"; then
                echo "Error: ${dir}/SKILL.md missing 'name' field"
                exit 1
              fi
              if ! grep -q "^description:" "${dir}/SKILL.md"; then
                echo "Error: ${dir}/SKILL.md missing 'description' field"
                exit 1
              fi

              # Check reference.md exists (optional)
              if [ -f "${dir}/reference.md" ]; then
                echo "✓ ${dir}/reference.md found"
              fi

              # Check examples.md exists (optional)
              if [ -f "${dir}/examples.md" ]; then
                echo "✓ ${dir}/examples.md found"
              fi
            fi
          done

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [markdown-lint, yaml-validation, link-checker, file-validation]
    if: always()
    steps:
      - name: Check results
        run: |
          if [ "${{ needs.markdown-lint.result }}" != "success" ] || \
             [ "${{ needs.yaml-validation.result }}" != "success" ] || \
             [ "${{ needs.link-checker.result }}" != "success" ] || \
             [ "${{ needs.file-validation.result }}" != "success" ]; then
            echo "❌ CI failed"
            exit 1
          else
            echo "✅ All CI checks passed"
          fi
